version: 2.1

jobs:
  build:
    docker:
      - image: node:12-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run postinstall
      - run: npm run build
  test-qbittorrent:
    docker:
      - image: node:12-buster
      - image: linuxserver/qbittorrent
    steps:
      - run: npm test -- -g qbittorrent
  test-transmission:
    docker:
      - image: node:12-buster
      - image: linuxserver/transmission
    steps:
      - run: npm test -- -g transmission

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-qbittorrent:
          requires:
            - build
      - test-transmission:
          requires:
            - build
