orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  docker:
    steps:
      - setup_remote_docker:
        version: 19.03.13

workflows:
  app-tests:
    jobs:
      - node/test:
        requires:
          - docker