version: 2.1

jobs:
  test:
    docker:
      - image: node:12-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - setup_remote_docker:
          version: 19.03.13
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test